### ISSUE TITLE
Logic doesn't correctly honor the case where elasticsearch_home is provided as kwargs

### ISSUE THREAD

**Issue by svenstaro** [tk0miya/testing.elasticsearch#1]
I construct the object like this:

`testing.elasticsearch.Elasticsearch(elasticsearch_home='somewhere')`

In initalize(self) you account for this in the first part like this:

```
    def initialize(self):
        self.elasticsearch_home = self.settings.get('elasticsearch_home')
        if self.elasticsearch_home is None:
            self.elasticsearch_home = find_elasticsearch_home()
```

but not in the later part of the function where you call `elasticsearch_yaml_path = find_elasticsearch_yaml_path()` which in turn calls `find_elasticsearch_home()` inside itself which ignores the self.elasticsearch_home set before.

**Comment by svenstaro** [comment]
I suggest for `find_elasticsearch_yaml_path()` to allow taking an argument `elasticsearch_home` (like so: `find_elasticsearch_yaml_path(elasticsearch_home=None)`) that will be trusted if it exists and otherwise `find_elasticsearch_home()` is called inside `find_elasticsearch_yaml_path()` as usual.

**Comment by tk0miya** [comment]
Agreed. `find_elasticsearch_yaml_path()` should be refer the `elasticsearch_home` argument.

**Comment by tk0miya** [comment]
Fixed at 3ee6c19.
Thank you for reporting.

**Comment by svenstaro** [comment]
Ok cool. Can you make a new release with this fix?

**Comment by tk0miya** [comment]
Sorry for late response. Now I released new package.
Thanks,
