### ISSUE TITLE
This tool should warn when a provided ES_HOME path is relative

### ISSUE THREAD

**Issue by svenstaro** [tk0miya/testing.elasticsearch#2]
Currently this package assumes paths to be absolute and everything breaks when the provided path is relative. I suggest the tool should warn, abort or try to make the path absolute. At any rate, this needs to be documented.

This should not only work with the `ES_HOME` env var but also with with the kwargs `elasticsearch_home` once #1 is fixed.

**Comment by tk0miya** [comment]
Fixed at 0648c89. I make it absolute simply.
Thank you for reporting.
