### ISSUE TITLE
Is there a way to get it  working with haystack and elasticsearch stack?

### ISSUE THREAD

**Issue by millerf** [tk0miya/testing.elasticsearch#5]
Hi,

I am trying to degaub haystack. How could I pass this new elasticsearch config to haystack duing testing?

**Comment by tk0miya** [comment]
Sorry, I don't know about haystack.

BTW, there are no way to customize elasticsearch config in proper way. So please override `Elasticsearch#initialize()` method to customize it.

Thanks,
